### ISSUE TITLE
Vocabulary values - test IPs for each allowed value vs just one

### ISSUE THREAD

**Issue by koit** [DILCISBoard/eark-ip-test-corpus#11]
**In case of elements/attributes with fixed vocabulary values, should we have a separate valid IP for each vocabulary value or just one valid IP with a random pick from the vocabulary?**

E.g. `mets/@CONTENTTYPESPECIFICATION` MUST have a value from a fixed vocabulary of `[ SMURFERMS | SMURFSFSB | SIARD1 | SIARD2 | SIARDDK | GeoVectorGML | GeoRasterGeotiff | MIXED | OTHER ]`

Should we create 9 separate IPs to test if the validator correctly reports the value as valid:

IP1 METS.xml:

`<mets CONTENTTYPESPECIFICATION = "SMURFERMS"/>`

IP2 METS.xml:

`<mets CONTENTTYPESPECIFICATION = "SMURFSFSB"/>`

IP3 METS.xml:

`<mets CONTENTTYPESPECIFICATION = "SIARD1"/>`

and so on. Or should we have just one IP with a random value from the vocabulary?

**Comment by carlwilson** [comment]
I think we should provide full coverage of valid cases. This is the case where we might use automation from a template and a list of values to generate the packages.

**Comment by carlwilson** [comment]
@koit to count number of cases and assess scale of problem, then decide whether to automate or not.
