### ISSUE TITLE
Tabs vs spaces indentation

### ISSUE THREAD

**Issue by koit** [DILCISBoard/eark-ip-test-corpus#12]
As we are moving to XML based descriptions of test cases, we face the question:

**Should we use tabs or spaces for indentation?**

There are good [arguments for both options](https://softwareengineering.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e) and both are indeed [seen in wide use](https://ukupat.github.io/tabs-or-spaces/). In the end, it does not matter which convention to use, [important is to pick a side](https://medium.com/@igorrinkovec/why-tabs-vs-spaces-debate-is-pointless-4b6e60d65b88) and then use it consistently across the project.

I tend to favour tabs, but I'm also perfectly fine with spaces, especially since developers who use spaces [make 8.6% more money than those who use tabs.](https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/)

Is there already a convention in commons-ip and other E-ARK code bases? Following the existing practice would be the most reasonable option.

**Comment by koit** [comment]
I think the answer is we should go for spaces because we work in GitHub and the way it displays tabbed indentation is really annoying (1 Tab = 8 spaces):

![tab indentation in gh displays as 8 spaces](https://user-images.githubusercontent.com/1552794/46478941-a772c900-c7f6-11e8-8553-b8e9c8234d9e.png)

I propose we settle to 2 spaces (as is done in [test case XML template description](https://github.com/DILCISBoard/eark-ip-test-corpus/blob/doc/validation-process/TESTCASES.md)).

**Comment by carlwilson** [comment]
Go for 2 spaces for indentation, I'll add a pre-commit check to ensure that the indentation is checked and fixed, then close the issue.

**Comment by carlwilson** [comment]
Stalled on a proper pre-commit hook ATM.
