### ISSUE TITLE
Falsely named METS.xml

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/eark-ip-test-corpus#13]
I am looking at this invalid example:

https://github.com/DILCISBoard/eark-ip-test-corpus/tree/liisi/corpus/structure/root/invalid/METS_falselynamed 

I propose @ltaimre that we have more falsely named METS files. These could be:

" METS".xml - whitespace in front
"METS ".xml - whitespace at back
"old_METS".xml - sign in front
"METS_old".xml - sign at back
"METS.xml".xml - file extension given in the name

I think we should use valid METS-files with wrong names to make sure that it is only the name that will trigger an error message.

**Comment by ltaimre** [comment]
Tnx for additional testingideas. Added several ones and put them into separate folder (on branch "liisi")

About whitspace - I think windows corrects whitespaces automatically, at least I wasnt able to produce files with whitspace in the front/back of the filename.

Valid METS files. Talked about it with @carlwilson  some weeks ago and he thought that completely empty files would be best for folder structure related test-cases. Did I understood right, @carlwilson?

**Comment by carlwilson** [comment]
Sorry, yes you understood correctly. Since we're only checking the structure we don't need METS contents but I like the idea of extra name cases. We should also include some that cover extra extension cases, e.g.
```
METS.old.xml
METS.xml.old.xml
```

**Comment by carlwilson** [comment]
These have been done now so closing the issue.
