### ISSUE TITLE
Is there a need for identifying CSIP req. in the METS XML instance? And if so, could a XML processing instruction be used?

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/eark-ip-test-corpus#14]
We may have a need for identifying CSIP req. in the METS XML instance apart from just using XML comments. If so, could a XML processing instruction be used?
```xml <?CSIref CSIPxxx?>```

```xml
<metsHdr RECORDSTATUS="NEW" CREATEDATE="2015-12-14T14:20:00" 
		LASTMODDATE="2015-12-14T14:20:00"> <?CSIref CSIP7?> <!-- CS - LASTMODDATA only mandatory if different from CREATEDATA -->
```

**Comment by carlwilson** [comment]
This is more to do with updating references after the specification changes than parsing links.

**Comment by carlwilson** [comment]
We’re using comments for this rather than processing instructions so closing this.
