### ISSUE TITLE
Update testcase.xml

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/eark-ip-test-corpus#184]
I am currently trying to create testcase.xml and packages to the test corpus. 
This .xml:
https://github.com/DILCISBoard/eark-ip-test-corpus/blob/integration/test-case.xml 

 is not updated to the current schema we agreed on.

**Comment by carlwilson** [comment]
See this PR that was awaiting review and is now closed: 
https://github.com/DILCISBoard/eark-ip-test-corpus/pull/181
