### ISSUE TITLE
Linking to a specific requirement - lacks of anchors in the specification

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/eark-ip-test-corpus#191]
We refer to the requirements with an URL, but we have no anchors in the spec.
Example for CSIP32 - only anchor is the heading of the chapter.
http://earkcsip.dilcis.eu/#534-use-of-the-mets-administrative-metadata-section-element-amdsec

**Comment by carlwilson** [comment]
Hi @andersbonielsen there is an anchor for each requirment, for CSIP32 use: http://earkcsip.dilcis.eu/#CSIP32

If that's OK let me know and I'll close this issue.

**Comment by andersbonielsen** [comment]
Yes, it turned out to be my browser (Firefox) that did not respond correctly.
