### ISSUE TITLE
Refering to representation folder in Error messages.

### ISSUE THREAD

**Issue by ltaimre** [DILCISBoard/eark-ip-test-corpus#36]
When writing error messages about representation folder. Should we stick to the general term "representation folder" or should we use variable [FOLDERNAME].

**Comment by PhillipTommerholt** [comment]
There can be several representation folders, so I think we should use the variable [FOLDERNAME]

**Comment by carlwilson** [comment]
In time we use the folder name and report but I’d like to dodge variable error messages at first. We keep this open and schedule variable messages sometime soon.

**Comment by ltaimre** [comment]
How is it now with the variable names?

It seems that is is also good to list also file names as variables. E.g. in CSIPSTR13  [TestCase.xml ](https://github.com/DILCISBoard/eark-ip-test-corpus/blob/csip/struct/csipstr13/corpus/structure/CSIPSTR13/testCase.xml)(rule 2)
