### ISSUE TITLE
Adding schemas to minimal IP?

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/eark-ip-test-corpus#37]
CSIPSTR15 recommends to have schema documents in schemas. Should minimal IP reflect this @carlwilson ? 

When I am creating error packages for the METS.xml I would like to validate my package to make sure I am not unknowingly introducing other errors or creating packages that would otherwise be caught with normal validation errors. This means that I am:

1 changing the root mets element in order to associate schemas
2 validating the xml
3 changing root mets element back to the basis

(Maybe I don't know of a possibility to associate schemas by not changing the root element)

**Comment by carlwilson** [comment]
The minimal document should be schema aware, do you mind making he changes there as a PR please?
