### ISSUE TITLE
Namespaces - Test corpora 

### ISSUE THREAD

**Issue by JoaoGomes2110** [DILCISBoard/eark-ip-test-corpus#381]
The namespaces were set with **"DILCIS"** in upper case when they should have been in lower case. 
E.g xmlns:csip="https://**DILCIS**.eu/XML/METS/C SIPExtensionMETS".

**Comment by carlwilson** [comment]
@JoaoGomes2110 can you quote your source for the correct case here? We're using the METS profile as our master source and these all use upper case in the identifier. For reference check:

- line 6 of: <https://earkcsip.dilcis.eu/profile/E-ARK-CSIP.xml>;
- line 7 & 8 of: <https://earksip.dilcis.eu/profile/E-ARK-SIP.xml>; and
- line 7 & 8 of: <https://earkdip.dilcis.eu/profile/E-ARK-DIP.xml>

While I'd agree that lower case would be more convenient the upper case construct is the officially endorsed one I believe?

**Comment by JoaoGomes2110** [comment]
In the CSIP 2.0.4 specification document, the mets.xml examples appear with the name dilcis in lower case and not in upper case. Also in the version of commons-ip the namespace is also in lower case. 
Example taken from the CSIP2.0.4 specification: 
![image](https://user-images.githubusercontent.com/17931713/130049782-dc3643dc-3240-4e60-9eb6-12701906f808.png)

Source: https://earkcsip.dilcis.eu/#useofmets.

**Comment by carlwilson** [comment]
OK, so we have a conflict between the examples and the profile. I'm going to ask @karinbredenberg to be an adjudicator here. My first instinct is to correct the examples but we may get the real intention from Karin.

**Comment by carlwilson** [comment]
@JoaoGomes2110 having checked the profile and the other examples it seems that you have found the only namespace ID case typo in the specification. This has been resolved as a typo in that particular example. The upper case namespace is the one used in the schema document: https://earkcsip.dilcis.eu/schema/DILCISExtensionMETS.xsd. The PR to fix the example is here: DILCISBoard/E-ARK-CSIP#656. This can be closed if you agree or when the PR is reviewed and merged by Karin.

**Comment by JoaoGomes2110** [comment]
> @JoaoGomes2110 having checked the profile and the other examples it seems that you have found the only namespace ID case typo in the specification. This has been resolved as a typo in that particular example. The upper case namespace is the one used in the schema document: https://earkcsip.dilcis.eu/schema/DILCISExtensionMETS.xsd. The PR to fix the example is here: [DILCISBoard/E-ARK-CSIP#656](https://github.com/DILCISBoard/E-ARK-CSIP/pull/656). This can be closed if you agree or when the PR is reviewed and merged by Karin.

Thank you for the clarification @carlwilson. I think this can be closed.
