### ISSUE TITLE
CSIP32 - Requirement Interpretation

### ISSUE THREAD

**Issue by JoaoGomes2110** [DILCISBoard/eark-ip-test-corpus#432]
In CSIP32 our interpretation is that the files under preservation MUST all be defined in digiprovMD and that these files SHOULD be named as defined in the guidelines.
But the overall requirement is defined as SHOULD.
So, files under preservation folder MUST or SHOULD be all defined in digiprovMD?

![image](https://user-images.githubusercontent.com/17931713/128528676-0335da86-8345-4358-97b5-2e4063fa1f54.png)

**Comment by PhillipAasvangTommerholt** [comment]
Our interpretation can be seen here: https://github.com/DILCISBoard/eark-ip-test-corpus/blob/integration/corpus/CSIP/CSIP32/testCase.xml

If there are no files in the preservation folder and no digiprovMD-element - then the validator should prompt a warning.
If there are files in the preservation folder and no digiprovMD-element - then the validator should prompt an error.
If there are no files  in the preservation folder and a digiprovMD-element - then the validator should prompt a warning.


I think I am most unsure about the last one. But how does this interpretation sound? It could be lifted to the owner of the specification.

**Comment by PhillipAasvangTommerholt** [comment]
I am closing this for now. Will re-open if needed.
