### ISSUE TITLE
Test cases for all XML elements vs only CSIP-specific

### ISSUE THREAD

**Issue by koit** [DILCISBoard/eark-ip-test-corpus#6]
**Should we create test cases for all XML elements/attributes that are found in CSIP or only the ones that are specific to CSIP?**

E.g. should we test for the existence of `<mets>` root element, knowing that standard METS validators already do it.

Koit's opinion: assuming the existence of accurate METS validators, creating test cases for generic METS XML seems unnecessary.

**Comment by carlwilson** [comment]
Test cases that should be caught by schema aware XML validation are considered out of scope. This has been documented in #15 and this issue will be closed once that's merged.
