### ISSUE TITLE
CSIP18 Test Case Description (out of scope)

### ISSUE THREAD

**Issue by carlwilson** [DILCISBoard/eark-ip-test-corpus#63]
**Specification:**
- **Name:** E-ARK CSIP
- **Version:** 2.0-DRAFT
- **URL:** http://earkcsip.dilcis.eu/

**Requirement:**
- **Id:** CSIP18
- **Link:** http://earkcsip.dilcis.eu/#CSIP18

**Error Level:** ERROR

**Description:** CSIP18 is a requirement which is identical with 26 other requirements in CS IP, since it is a requirement for the use of ID's in accordance with the XML-standard. IDs are used multiple times in the elements of METS. The requirement links to http://earkcsip.dilcis.eu/#the-use-of-identifiers 

The requirements for the use of identifiers are several: 

1. There MUST be one ID-attribute. _**(Will be tested with general schema validation)**_
2. ID MUST begin with a letter, or an underscore character (‘_’). _**(Will be tested with general schema validation)**_
3. ID  MUST contain no characters other than letters, digits, hyphens, underscores, full stops, and certain combining and extension characters. **_(Will be tested with general schema validation)_**
4. ID MUST start with a prefix, followed by the value of the identifier.
5. It is required that any selected prefix is used consistently throughout the package.
6. It MUST be unique within the package. **_(Will be tested with general schema validation)_** 

4, and 5 is hard to test, as there is no place where the prefix can be identified.

**Comment by PhillipTommerholt** [comment]
Should I create a testCase.xml with the value TESTABLE FALSE?

https://github.com/DILCISBoard/eark-ip-test-corpus/issues/79#issuecomment-483188993

**Comment by carlwilson** [comment]
Again yes @PhillipTommerholt thanks
