### ISSUE TITLE
CSIP21 Test Case Description

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/eark-ip-test-corpus#75]
**Specification:**

* **Name:** E-ARK CSIP
* **Version:** 2.0-DRAFT
* **URL:** http://earkcsip.dilcis.eu/

**Requirement:**

* **Id:** CSIP21
* **Link:** http://earkcsip.dilcis.eu/#CSIP21

**Error Level:** WARNING

**Description:** The mdRef-element SHOULD be there. Therefore a warning should be presented if a package has no mdRef-element. The problem here is that the correctness of there being a mdRef-element or not really relies on whether there is a descriptive metadata file or not. The current CSIP21 does not take this into consideration. I would as an user be more interested in knowing:

WARNING: There are no files in  the folder: `/metadata/descriptive` and no information on descriptive metadata files in METS.xml (mdRef).

ERROR: There are files in  the folder: `/metadata/descriptive` but no information about descriptive metadata files in METS.xml ( via mdRef).

ERROR: There is information about descriptive metadata files in METS.xml ( via mdRef)  but no files in  the folder: `/metadata/descriptive`

**Comment by andersbonielsen** [comment]
That is more or less what I tried to do in test case  CSIP17: #62 
https://github.com/DILCISBoard/eark-ip-test-corpus/blob/csip/dmdSec/CSIP17/test-case.xml.
Carl @carlwilson said that he would try to find a general approach for metadata - file "integrity checks" or "coherence checks" or "reference checks" or whatever they should be defined as in English.
