### ISSUE TITLE
CSIP29 Test Case Decription

### ISSUE THREAD

**Issue by PhillipTommerholt** [DILCISBoard/eark-ip-test-corpus#77]
**Specification:**

* **Name:** E-ARK CSIP
* **Version:** 2.0-DRAFT
* **URL:** http://earkcsip.dilcis.eu/

**Requirement:**

* **Id:** CSIP29
* **Link:** http://earkcsip.dilcis.eu/#CSIP29

**Error Level:** ERROR 

**Description:** 

The checksum of the linked file. 1..1 MUST.

It is mandatory in CS IP but optional in METS. 
Therefore it should test: 
- whether the attribute exists
- whether the checksum is correct. 

There is a dependency to CSIP30, since it must be stated what kind of checksum type it is before it can be checked whether the checksum is correct or not.

**Comment by andersbonielsen** [comment]
Take care Phillip, you are using an image. What happens if the spec changes?
**Description:** ![image](https://user-images.githubusercontent.com/15984159/52411303-9eaf3e00-2adb-11e9-99f2-c8a3bb12cd6f.png)

**Comment by PhillipTommerholt** [comment]
> Take care Phillip, you are using an image. What happens if the spec changes?
> **Description:** ![image](https://user-images.githubusercontent.com/15984159/52411303-9eaf3e00-2adb-11e9-99f2-c8a3bb12cd6f.png)

Fixed (but for an overview I really need to see the actual requirement when creating these). If the spec changes I guess there also might be other alterations needed in the description.
