### ISSUE TITLE
CSIP25 Test Case Description (out of scope)

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/eark-ip-test-corpus#79]
**Specification:**
- **Name:** E-ARK CSIP
- **Version:** 2.0-DRAFT
- **URL:** http://earkcsip.dilcis.eu/

**Requirement:**
- **Id:** CSIP25
- **Link:** http://earkcsip.dilcis.eu/#CSIP25

**Error Level:** ERROR

**Description:** Specifies the type of metadata in the linked file. Values are taken from the list provided by the standard, i.e. the METS standard. `dmdSec/mdRef/@MDTYPE`

Regarded *Out of scope*: https://github.com/DILCISBoard/eark-ip-test-corpus#out-of-scope
Existence of mandatory attribute and check of valid values handled by XML Schema Validation.
No need for test-case.xml or corpus.

**Comment by PhillipTommerholt** [comment]
> No need for test-case.xml or corpus.

In the testCase.xml we have an element called "TESTABLE". 
Should we still create the testCase.xml and just enter the value "FALSE" here @carlwilson ?

**Comment by carlwilson** [comment]
Yes please @PhillipTommerholt as we can automatically ignore them.
