### ISSUE TITLE
Test cases fully atomic vs one per XML element or attribute

### ISSUE THREAD

**Issue by koit** [DILCISBoard/eark-ip-test-corpus#8]
**Should we have fully atomic test cases or one per XML element/attribute (i.e. one per row in the tables of CSIP chapter 5.3)?**

E.g. the description of `mets/@TYPE` is:

> Mandatory in this specification. The TYPE attribute must be used for identifying the type of the package (genre), for example ERMS, RDBMS, digitised construction plans. However, there is no fixed vocabulary and as such implementers are welcome to use values most suitable for their needs.

This can be broken down to two rules:
* `mets/@TYPE` MUST be present
* `mets/@TYPE` MUST have a non-empty value

We could have separate test cases for each rule or one test case that covers both.

---

Koit's opinion: one test case per row of CSIP is clearer, as we shall always have exactly one test case for each element/attribute, no matter how complicated the rules. The current style of rule identifiers also favours this approach as `mets/@TYPE` is identified as CSIP3 and it is easier to have all the details of CSIP3 covered by one test case.

**Comment by carlwilson** [comment]
I agree here that a single test case can cover all attribute values is desirable here. It might present an opportunity for automation from a template and list of values if there's a significant number "valid value set" test cases.
