### ISSUE TITLE
CSIP30 Test Case Decription

### ISSUE THREAD

**Issue by andersbonielsen** [DILCISBoard/eark-ip-test-corpus#83]
**Specification:**

* **Name:** E-ARK CSIP
* **Version:** 2.0-DRAFT
* **URL:** http://earkcsip.dilcis.eu/

**Requirement:**

* **Id:** CSIP30
* **Link:** http://earkcsip.dilcis.eu/#CSIP30

**Error Level:** ERROR 

**Description:** 

CSIP30 | File checksum type  dmdSec/mdRef/@CHECKSUMTYPE | The type of checksum following the value list in the standard which used for the linked file. | 1..1  MUST
-- | -- | -- | --

It has cardinality '1..1' and level 'MUST' in CSIP.
It is mandatory in CSIP but optional in METS. 
Rule needed for the existence of the attribute `CHECKSUMTYPE` for element `dmdSec/mdRef`.
ERROR if it does not exists.
No rule needed for the the value of the attribute, it is validated by XML Schema.

**Comment by carlwilson** [comment]
We still need test cases for bad checksum values.
